Development
digipolisantwerp/probes_module_nodejs pull request #1
Opened 2020-03-25 17:29 UTC by Jan-Bart

2020-03-25 21:37 UTC, stefanpante requested changes
rewrite your Promise handling. It contains redundant logic.

2020-03-25 21:37 UTC, stefanpante commented on src/controller.js
> +      await Promise
why combine await with then they do the same thing?

2020-03-25 21:37 UTC, stefanpante commented on src/controller.js
> +      await Promise
you could just write this as 
```javascript
try {
  await Promise.all(alive.map(check => check()));
  return res.json({...})
} catch (error) {
      console.error(`PROBES_ERROR_2: ${error.message || ''}`);
      return res.status(error.status || 500).json({ message: error.message || '' });
}
```

2020-03-25 21:37 UTC, stefanpante commented on src/controller.js
> +        .then(() => {
same remark as above

2020-03-26 07:06 UTC, vademo approved these changes
Only minor remarks ;)

2020-03-26 07:06 UTC, vademo commented on .travis.yml
> +  - "11"
12, 13

2020-03-26 08:54 UTC, stefanpante approved these changes

2020-03-26 08:56 UTC, merged